### ISSUE TITLE
Can't decode large .pdb files Octave

### ISSUE THREAD

**Issue by Delgon95** [BGSU-RNA/FR3D#8]
Im using zGetNTData to load .pdb files. Everything is ok when file is not so big but files like 1S72.pdb does not give any output, there are 0 interactions. Weird thing is that it is working on OS X with 4.0.3 octave but is not on Ubuntu 16.04 with octave 4.0.0, 4.0.2, 4.0.3, 4.2.0.

**Comment by clzirbel** [comment]
Dear Michał,

Thank you for writing about FR3D.  I'm sorry that I haven't been able to 
get back to you about this.  I have used FR3D with Octave, but found it 
to be very slow on annotating PDB files, and so have not used it for 
that very much.  Hopefully you managed to figure out what could be done 
with Octave to make this work better.  If you are running zAddNTData, 
you can run it in verbose mode, zAddNTData('1S72',0,[],1) so it will 
give you more information about what it is doing.

Craig

______________________________________________________________________
*Craig L. Zirbel*
Professor and Graduate Coordinator
Department of Mathematics and Statistics
BGSU | Bowling Green State University
Bowling Green, OH 43403
+1-419-372-7466; zirbel@bgsu.edu <mailto:zirbel@bgsu.edu>
http://www-math.bgsu.edu/~zirbel <http://www-math.bgsu.edu/%7Ezirbel>
______________________________________________________________________

**Comment by Delgon95** [comment]
It is working in version 3.8.0.
Yes, reading function zReadPDBTextReadNew is very slow in octave. Found out that just making T variable takes 150s on 1S72.pdb but only 0.5s in MatLab. Other functions executed in Octave are around 3-6 times slower compared to MatLab.
